### ISSUE TITLE
Question Redis with password

### ISSUE THREAD

**Issue by jackbit** [spk/maman#4]
It seems not working if using redis with password, any suggest redis://username:password@127.0.0.1:6593/0 ?

**Comment by spk** [comment]
I just tried locally with `requirepass foobared` option on redis.conf and with `REDIS_URL="redis://:foobared@127.0.0.1/"` and it worked for me, maybe you have a password with non utf8 chars cf https://github.com/mitsuhiko/redis-rs/pull/163 ?
Let me know how you setup your redis and your REDIS_URL to reproduce if its not that
